
version: '3'

services:  
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
      POSTGRES_DB: employees

    ports:
      - "5432:5432"

