CREATE DATABASE EMPLOYEES

CREATE TABLE EMPLOYEES(
   ID             SERIAL  PRIMARY KEY,
   NAME           TEXT    NOT NULL,
   CPF            VARCHAR(15) NOT NULL,
   PHONE          VARCHAR(50),
   EMAIL          VARCHAR(50) NOT NULL,
   BIRTH_DATE     DATE    NOT NULL,
   HIRE_DATE      DATE    NOT NULL

);